SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS "NOME DE CLIENTE", BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;
SELECT CPF AS IDENTIFICADOR, NOME AS "NOME DE CLIENTE", TDC.BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;
SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;


SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=1;

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '1000889';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Uva';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET';

SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE > 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 20; -- <> É NINGUEM TEM 20 ANOS
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO>= '14/11/95';
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE BETWEEN 19 AND 22;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO = '470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO = '470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Laranja' OR SABOR = 'Melancia';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('Manga', 'Laranja','Melancia');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('Manga', 'Laranja','Melancia') AND TAMANHO = '1 Litro';

SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro','Sao Paulo') AND IDADE > =20;
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro','Sao Paulo') AND IDADE > =20 and IDADE <= 25;
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro','Sao Paulo') AND IDADE BETWEEN 20 and 25;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Lima/Limao', 'Morango/Limao');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao';