SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM NOTAS_FISCAIS;
SELECT MATRICULA, COUNT(*) AS NUMEROS_DE_NOTAS FROM NOTAS_FISCAIS GROUP BY MATRICULA;
SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*) AS NUMERO_DE_NOTAS
FROM TABELA_DE_VENDEDORES
INNER JOIN NOTAS_FISCAIS
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;

SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS NUMERO_DE_NOTAS
FROM TABELA_DE_VENDEDORES TV
INNER JOIN NOTAS_FISCAIS NF
ON NF.MATRICULA = TV.MATRICULA
GROUP BY NF.MATRICULA, TV.NOME;

SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
,TC.NOME AS NOME_DO_CLIENTE
,NF.CPF AS CPF_NOTAS_FICAIS
FROM
TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_CLIENTES;

INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, 
SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) 
VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', '', 'Bangu', 'Rio de Janeiro', 
'RJ', '23400000', TO_DATE('1989-02-04','YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);

SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
,TC.NOME AS NOME_DO_CLIENTE
,NF.CPF AS CPF_NOTAS_FICAIS
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF WHERE NF.CPF IS NULL;

SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
,TC.NOME AS NOME_DO_CLIENTE
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF WHERE NF.CPF IS NULL;
SELECT
FROM TABELA_DE_CLIENTES TC
INNER JOIN TABELA_DE_VENDEDORES TV
SELECT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE
FROM TABELA_DE_CLIENTES TC
INNER JOIN TABELA_DE_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO;
SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE
FROM TABELA_DE_CLIENTES TC
LEFT JOIN TABELA_DE_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO;
SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE
FROM TABELA_DE_CLIENTES TC
RIGHT JOIN TABELA_DE_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO;
SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE
FROM TABELA_DE_CLIENTES TC
FULL JOIN TABELA_DE_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO;

SELECT CLIENTE, CIDADE, ESTADO
FROM CLIENTE
UNION
SELECT FORNECEDOR CIDADE, ESTADO
FROM FORNECEDOR;
SELECT CLIENTE AS CLI_FOR, CIDADE, ESTADO
FROM CLIENTE
UNION
SELECT FORNECEDOR CIDADE, ESTADO
FROM FORNECEDOR;
SELECT CIDADE, ESTADO
FROM CLIENTE
UNION
SELECT CIDADE, ESTADO
FROM FORNECEDOR;

SELECT CIDADE, ESTADO
FROM CLIENTE
UNION ALL
SELECT CIDADE, ESTADO
FROM FORNECEDOR;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;


SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;


SELECT * FROM MOVIMENTO WHERE CLIENTE IN ('CLIENTE 1');

SELECT * FROM MOVIMENTO WHERE CLIENTE IN ('CLIENTE 1', 'CLIENTE 2');

SELECT CLIENTE FROM CLIENTE WHERE NUM_FUNC = 10;

SELECT * FROM MOVIMENTO WHERE CLIENTE IN ('CLIENTE 1', 'CLIENTE 2');

SELECT * FROM MOVIMENTO WHERE CLIENTE IN (SELECT CLIENTE FROM CLIENTE WHERE NUM_FUNC = 10);
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO IN (
'Tijuca',
'Jardins',
'Copacabana',
'Santo Amaro');
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO IN
(SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);


SELECT
ESTADO,
SUM(NUM_FUNC)
FROM 
CLIENTE
GROUP BY ESTADO

SELECT ESTADO,
SUM(NUM_FUNC)
FROM CLIENTE
GROUP BY ESTADO
HAVING
SUM(NUM_FUNC) >= 60

SELECT ESTADO,
SUM(NUM_FUNC)
FROM CLIENTE
GROUP BY ESTADO

SELECT ESTADO,
NUM_FUNC
FROM ESTADO_FUNC
WHERE NUM_FUNC 
>=60

SELECT ESTADO,
NUM_FUNC
FROM (
SELECT ESTADO,
SUM(NUM_FUNC)
FROM CLIENTE
GROUP BY ESTADO
)
WHERE NUM_FUNC
>= 60

SELECT ESTADO_FUNC.ESTADO,
ESTADO_FUNC.NUM_FUNC
FROM (
SELECT ESTADO,
SUM(NUM_FUNC)
FROM CLIENTE
GROUP BY ESTADO
) ESTADO_FUNC
WHERE NUM_FUNC
>= 60

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) >= 80;

SELECT SOMA_EMBALAGENS.EMBALAGEM, SOMA_EMBALAGENS.SOMA_PRECO
FROM
(
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
) SOMA_EMBALAGENS
WHERE SOMA_EMBALAGENS.SOMA_PRECO >= 80;

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
) SOMA_EMBALAGENS
WHERE SOMA_EMBALAGENS.SOMA_PRECO >= 80;

CREATE VIEW VW_SOMA_EMBALAGENS AS
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO 
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;


SELECT EMBALAGEM, SOMA_PRECO FROM VW_SOMA_EMBALAGENS
WHERE SOMA_PRECO >= 80;

SELECT * FROM TABELA_DE_PRODUTOS TP
INNER JOIN VW_SOMA_EMBALAGENS VW
ON TP.EMBALAGEM = VW.EMBALAGEM
WHERE VW.SOMA_PRECO >= 80