SELECT * FROM TABELA_DE_PRODUTOS;
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';

SELECT * FROM CLIENTE;
SELECT * FROM CLIENTE WHERE ROWNUM <= 4;
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT ROWNUM, TABELA_DE_PRODUTOS.* FROM TABELA_DE_PRODUTOS;
SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP;
SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <= 5;
SELECT TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <= 5;
SELECT TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM >= 2 AND ROWNUM <= 3;

SELECT * FROM CLIENTE ORDER BY DATA_COMP;
SELECT * FROM CLIENTE ORDER BY DATA_COMP DESC;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO DESC;

SELECT ESTADO, SUM(NUM_FUNC) FROM CLIENTE GROUP BY ESTADO;
SELECT ESTADO, MIN(NUM_FUNC) FROM CLIENTE GROUP BY ESTADO;
SELECT CIDADE, IDADE
FROM TABELA_DE_CLIENTES
ORDER BY CIDADE, IDADE;
SELECT DISTINCT CIDADE, IDADE
FROM TABELA_DE_CLIENTES
ORDER BY CIDADE, IDADE;
SELECT CIDADE, SUM(IDADE)
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE
ORDER BY CIDADE;
SELECT CIDADE, SUM(LIMITE_DE_CREDITO), SUM(IDADE)
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA)
FROM TABELA_DE_PRODUTOS;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA)
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;
SELECT EMBALAGEM, NOME_DO_PRODUTO
FROM TABELA_DE_PRODUTOS
ORDER BY EMBALAGEM;
SELECT EMBALAGEM, COUNT(*)
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
ORDER BY EMBALAGEM;
SELECT EMBALAGEM, COUNT(*)
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM
ORDER BY EMBALAGEM;
SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM
ORDER BY EMBALAGEM;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;


SELECT ESTADO SUM(NUM_FUNC) FROM CLIENTE GROUP BY ESTADO
SELECT ESTADO SUM(NUM_FUNC) FROM CLIENTE WHERE SUM(NUM_FUNC) >= 60 GROUP BY ESTADO
SELECT ESTADO, SUM(NUM_FUNC) FROM CLIENTE GROUP BY ESTADO HAVING SUM(NUM_FUNC) >= 60
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES GROUP BY ESTADO;
SELECT ESTADO, SUM(LIMITE_DE_CREDITO)
FROM TABELA_DE_CLIENTES
WHERE SUM(LIMITE_DE_CREDITO) >= 900000
GROUP BY ESTADO;
SELECT ESTADO, SUM(LIMITE_DE_CREDITO)
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 900000;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >= 20;

SELECT CLIENTE,
(CASE WHEN NUM_FUNC >= 20 THEN 'GRANDE'
)
SELECT CLIENTE,
(CASE
    WHEN NUM_FUNC >= 20 THEN 'GRANDE'
    ELSE 'PEQUENO'
END)
FROM CLIENTE
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA
FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
)
FROM TABELA_DE_PRODUTOS;
WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga';

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
ORDER BY CLASSIFICACAO;